language: node_js
node_js:
- lts/*
install:
- yarn install
addons:
  sonarcloud:
    organization: "hrslab"
    token:
      secure: adNuXfRCLGskOyxMGg2rmUsSd0vrtnXKfiOYBwP9pmHCbqMh1YG1VSWyoYKJkh6XWQopQCBlnoCPkXbMIZtb1a+s8fqgMofZT+BSfvUzi6JfUKGfVwB7Ql2kQe6WuRCNTbnufsTNe91UrMuwCS/IIQ3yVe4da9LckXyXcFVX79F4tZZ3cKzJR02XqU7xpHPm7elLfmaFtqj7AHFye3gI3JNSZBwPimXfZ7zhBJ44lLNROzkzVIpeS0b6GClACa2kx91f/HBuksdT2HydWinxEPZ2dYJxP21Mh/34f15GBcEx06trYvkiX/ez/37Yu9bfnvAZKiDz9X+hvrJoGTVFA8jqD9rsnIViYX9t9G5nTt48CwpjENg4PZt81wn+Fgy5zqsrBOnMZeYr9aY3glisK83tY0mcSOtcUa8FkF69XNnNWRkQ42I9EDFNKcx7U/rKngZhGHThnEN3dFD4/HyGGgANxA9WTERqXXO0sJhC5oZze6G4cAjJ55z16BYrPLttw2Mb+QogZ/6oNO3G+2z3msLcLWSN/fVzYj7IFr4fBfehR/kxKP58Y0m2DsnOgWjZYiF9o6vrKMq1A8OYffpA3phuaf5HlElnTI47QSEHNwUimzCM6a25AhtRa6d8c7y059vntdohgEGh9nGDRktAPJwwU9JtndDKMlWuzW2SPa8=

script:
- yarn docs:build
- sonar-scanner
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
    