---
language: node_js
node_js:
  - lts/*
install:
  - npm ci
addons:
  sonarcloud:
    organization: hrslab
    token:
      secure: nLyM43WMrMrAzWcMdmQ6oaMeiPuKxNzMnNB7Qra7Q+2m2mbUpZOO/Pw5WSSG4fOKgSwJQZM4y0xa7MpSGmQSplFTx+TUApeBMo8Fvv43IU8x3tX4bRoFb6UfDM5TEn8+A8Ghx12iGA1ZobJm7fZPsj8auUjGdx58mcHnpDXylUJ0H7+FlqqoJ5/oRrQSNd+IVq99EJgpCik11wVXl6e4WAHEBze+0UlF69Jmb3KC5TuU9v1xGbAbKSTYui04nM1Rs8Cg0riK9wE6lo5tGiMvaKTh47wlM2ugpoXHUhNv1SAx+VSGt74h00d8TzTgsXiezgzojubxpswyD4TOMi5wuRy81MH5nYCzv811tQL+aWzgI+tYGrDf8zStsV38+Mzwshh1mDv9ZuqeEzPkkmuGSgwnB3PaNzJUBsflYMlWfcVWIqiDsQUc6l7YePmI5oknbPEgEhovcmyL4M/SO5AD9FkunReUMNTOEO3SVl0WatkwRbe49VYkYEabUNiOkMw+aEdObLTx5jXsLWY6j9zNqxLCmOchUgEmj/brsKElW1AaIVUR6mlrpLQAY8C/3haObhttaID3Fh1XR2UcOehhJ7lYPg5eFTD7XFwLkAndADaBCl6+H5m2PiFaHg6q9a/xEJNH6lQa/rfV4WfZZhyM92cWe10bwIcPPhRsRm8z/xg=
script:
  - npm run docs:build
  - sonar-scanner
deploy:
  provider: pages
  local_dir: docs/.vuepress/dist
  github_token: $TRAVIS_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
env:
  global:
    secure: Jrf4ZAQ9D3qhOxCmbNAEhS7lPON9sO82oxX/2EoScJhMucGotSTNGBiFrfXR4miGTmRb6yjeIM0aou7KA4JaIdbwDSYIdqFjZWsUpioDMe2jTk//qhzRSiDG8MJhHN4Cim7SvPt4hyIcMuabIHTIxWEclY0r9PG6Zytlk0GSmwxWGt76DNLuzEywGKGDS/Y9FcteGcDxTXlmGB0+MY288L2hxilr+S/XK96bjw+w7VC09fL0NgUcEL7TrIU6TuzjNel/ctrxhPfjlimO6PTq5VARteK65kOfyECvCYUFvykGa2sMhv6N7gdHKo7N2kCsaJMCoQy2S+8xYKM0rLLfxvGc0kn++oWkeePQSWJPMUso/wtfhKtb1OuwAdgo7QNpiH4Bbi9ztjVReHmdxOusKZpn8qO5KJI8XSLU5JewZkH1oVwbFFWNggPZErZXjr2+EGiJfJpjGanPd9M8YFEvOkz4lfYTOV6zercAVoccpNJE4PSMTUxs04PuTJPCzZUUUx1wS8yYze2NhehVs2BMqHG/DaDeJwHnK7vYANN1MgjnztnrK8BJL7gRrb+dBAIVDQoozKT8EsHagzo5jcDiVGfMRp9fyeP1naUv1hGgUGj9AweUbFakJQzbrc7yVlFvvCsagdW8SLN8D3jQhC0I+UC98UtroZtk3aZbYoA2ync=
